
# all entries in this dict will have the following format.
# customer_code<int>: {'cc':['ccmailid1', ..], 'to': ['tomail id1', ..]}
# note that cc and to are should be added for every customer code 
# even if the lists are empty, other wise report generation will fail.


customer_emails_dict = {
    64278:{'cc':['ruchikas@ecomexpress.in'],'to':['warehouse@ariseindialtd.com', 'jha.logistics@ariseindialtd.com', 'am.ecommerce@ariseindialtd.com', 'ecommerce@ariseindialtd.com']},
    87254:{'cc':['sheetalt@ecomexpress.in'],'to':['seo@vidyaprakashan.com']},
    65280:{'cc':['javedh@ecomexpress.in', 'shabaazk@ecomexpress.in'],'to':['inlifehealthcare@outlook.com', 'prateek@inlifehealthcare.com']},
    74238:{'cc':['sheetalt@ecomexpress.in'],'to':['kuldeeps-cb@modi.com', 'alka-cb@modi.com', 'kunalg@modi.com']},
    31270:{'cc':[],'to':['karan@fitandglow.in', 'manish@fitandglow.in', 'arvind@fitandglow.in', 'bhavya@fitandglow.in', 'parth@fitandglow.in', 'logistics@fitandglow.in']},
    67272:{'cc':[],'to':['prabhat.kumar@suksh.com', 'murali@suksh.com', 'ndr@suksh.com']},
    77277:{'cc':[],'to':['hemanth.kumar@way2online.com', 'shalem.raju@way2online.com', 'ugendher.sc@way2online.com']},
    85184:{'cc':[],'to':['ca.aroraanuj@gmail.com']},
    56275:{'cc':[],'to':['riyaz@hasbroclothing.com', 'sriram@hasbroclothing.com', 'suhail@hasbroclothing.com']},
    73271:{'cc':['ruchikas@ecomexpress.in'], 'to':['nirdesh@checknshop.com', 'nirdeshpuri@gmail.com', 'support@checknshop.com', 'nirdesh@checknshop.com', 'checknshop414@gmail.com']},
    54269:{'cc':[], 'to':['accounts@nxiindia.com', 'marketing@nxiindia.com', 'sunilg@nxiindia.com', 'info@nxiindia.com']},
    62266:{'cc':['sheetalt@ecomexpress.in', 'rahuls@ecomexpress.in', 'SumitSehgal@ecomexpress.in'], 'to':['team@cartdeal.com', 'rahulb@cartdeal.com', 'krishan@cartdeal.com', 'bhaskar@cartdeal.com', 'Bhatt.rahul4u@gmail.com', 'Rahulsingh0915@gmail.com', 'krishangrover@gmail.com', 'bealchemist@gmail.com', 'rahulb@cartdeal.com']},
    15267:{'cc':['sushantg@ecomexpress.in'], 'to':['Nitin.narang@elitify.com', 'Ravisha.sirohi@elitify.com', 'Abhishek.jindal@elitify.com', 'vimlesh.kumar@elitify.com', 'nand.kishore@lavidaluxegroup.com']},
    29257:{'cc':['sandeepc@ecomexpress.in','Sumitsehgal@ecomexpress.in'], 'to':['yadav.ajit@adisports.co.in', 'jahngir.sunil@adisports.co.in']},
    95263:{'cc':['niteshc@ecomexpress.in'], 'to':["raghavs@arihantbooks.com","crm@arihantbooks.com","Ankur.eduweb@gmail.com","Sonakohli425@gmail.com"]},
    16252:{'cc':['rubys@ecomexpress.in'], 'to':[]},
    23244:{'cc':['amrins@ecomexpress.in', 'shalinia@ecomexpress.in', 'shankars@ecomexpress.in'],
           'to':['quickadvertising17@gmail.com','shaliniqs@gmail.com']},
    32190:{'cc':['amrins@ecomexpress.in', 'shalinia@ecomexpress.in', 'shankars@ecomexpress.in'],
           'to':['vasant@anandindia.in', 'helpdesk@anandindia.in']},
    22251:{'cc':[],'to':['youshop16@gmail.com']},
    18099:{'cc':[],'to':['himanshu@talamela.in']},
    50243:{'cc':[],'to':['rakeshs@giftingnation.com', 'srini.mothey@giftingnation.com', 'paramitam@giftingnation.com']},
    41147:{'cc':[],'to':['quickhairfiber@gmail.com']},
    75136:{'cc':[],'to':['info@flute.in']},
    50139:{'cc':[],'to':['bhuwalcreations@gmail.com']},
    12077:{'cc':[],'to':['Manupathania@ngalsonlinestore.com']},
    95078:{'cc':[],'to':['vivek.cottage@gmail.com']},
    69116:{'cc':[],'to':['Bikramjit.Singh@bikano.com']},
    51143:{'cc':[],'to':['admin@chiclique.com','contactus@chiclique.com']},    
    95105:{'cc':[],'to':['neerajmeht@gmail.com']},
    53130:{'cc':[],'to':['sapna.dalmia@srvcontrols.com','ritika.rana@srvcontrols.com']},
    17155:{'cc':[],'to':['heena@healthvistas.com','adnan@healthvistas.com']},
    54182:{'cc':[],'to':['praveen@shopllers.com']},
    81044:{'cc':[],'to':['nikhil@esutta.com','thapar.nikhil@gmail.com']},
    64109:{'cc':[],'to':['gandhi@ashopi.com']},
    71191:{'cc':['sijur@ecomexpress.in'],'to':['Pooja.jindal@joshmobiles.com','bdm@joshmobiles.com','subhash6ten@gmail.com','josh.support.tl@joshmobiles.com','mukundh@ecomexpress.in']},   
    96213:{'cc':[],'to':['akashjadaun@hotmail.com','avantika.verma@kewlinstyle.com','abhaysinghkewl@outlook.com','mukundh@ecomexpress.in']},
    90234:{'cc':['SumitSehgal@ecomexpress.in'],'to':['pkdoffer@gmail.com','tomarsachin1982@gmail.com','mukundh@ecomexpress.in']},
    45232:{'cc':[],'to':['support@makeupshades.com']},
    71222:{'cc':[],'to':['stylemygadget@gmail.com']},
    67201:{'cc':[" rubys@ecomexpress.in"],'to':['yogesh.kumar@tradus.com','bhola@tradus.com', 'amit.soni@tradus.com','mohan.agarwal@tradus.com', 'logistics@tradus.com']},
    45215:{'cc':[],'to':['yonitinh@gmail.com','rsinha@ecomexpress.in']},
    50197:{'cc':[],'to':['manaschugh@yahoo.com','contact.greenrock@gmail.com', 'shilpaa@ecomexpress.in', 'veenav@ecomexpress.in']},
    57210:{'cc':['kalpanak@ecomexpress.in'],'to':['jwalaautoelectronics@gmail.com', 'shilpaa@ecomexpress.in', 'veenav@ecomexpress.in']},
    20212:{'cc':[],'to':['moses@megaoffersale.com', 'shilpaa@ecomexpress.in', 'veenav@ecomexpress.in']},
    99188:{'cc':[],'to':['suhasini@yogabars.in', 'shilpaa@ecomexpress.in', 'veenav@ecomexpress.in']},
    61217:{'cc':[],'to':['operations@bhaap.com', 'varsha@bhaap.com', 'shilpaa@ecomexpress.in', 'veenav@ecomexpress.in']},
    64224:{'cc':[],'to':['cs.logistics@zovi.com' , 'tathagat@zovi.com', 'dayal.gupta@zovi.com', 'niraj@zovi.com', 'shilpaa@ecomexpress.in', 'veenav@ecomexpress.in','cs_logistics@zovi.com']},
    46214:{'cc':['rsinha@ecomexpress.in'],'to':['processcontrol@paytm.com','rsinha@ecomexpress.in','fulfillment@paytm.com','devendar.singh@paytm.com','maneesh.mittal@paytm.com','shipping@paytm.com', 'Shailja.narang@paytm.com', 'ffhelpdesk@paytm.com']},
    54149:{'cc':[],'to':['mohan.jha@m-eretail.com','ops@m-eretail.com']},
    94208:{'cc':['kalyan.krishna@pearson.com','shilpaa@ecomexpress.in','veenav@ecomexpress.in','shwethaj@ecomexpress.in'],'to':['anianilkumar.s@pearson.com','faiz.ulla@pearson.com','balasubramani.muniswany@pearson.com','Bibi.Ebrahim@pearson.com','Thanuja.Kabalishwaran@pearson.com','chaithra.shanthraj@pearson.com','louisa.lourdunathan@pearson.com','daniel.paul@pearson.com']},
    32205:{'cc':['kalpanak@ecomexpress.in','prasad.br@fashionara.com'],'to':['sunil.kumar@fashionara.com','naveen.gw@fashionara.com', 'shilpaa@ecomexpress.in', 'veenav@ecomexpress.in']},
    67068:{'cc':['sales@litejoy.co.in'],'to':['lokesh@litejoy.co.in']},
    93181:{'cc':[],'to':['azaz@imfab.co','pramod@imfab.co','kishan@sikaria.co','ajit@imfab.co']},
    20183:{'cc':['srajesh@ecomexpress.in','veenav@ecomexpress.in','shilpa@ecomexpress.in','shwethaj@ecomexpress.in'],'to':['anil@seajintech.com','anil@seajintech.com','anil@seajintech.com','anil@seajintech.com']},
    78168:{'cc':['srajesh@ecomexpress.in','veenav@ecomexpress.in','shilpa@ecomexpress.in','shwethaj@ecomexpress.in'],'to':['dispatch.rajdhanicotton@gmail.com','rajesh@rajdhanicotton.com','praseeth@rajdhanicotton.com','rahul@rajdhanicotton.com','Rc@rajdhanicotton.com','ravi@rajdhanicotton.com']},
    97199:{'cc':['Rajeshwars@ecomexpress.in',  'shankars@ecomexpress.in', 'amrins@ecomexpress.in', 'shalinia@ecomexpress.in'],'to':['e-com@savex.in','shafiq@savex.in','devakumar@savex.in','pawan@savex.in','yogita.shetye@savex.in', 'sanjay.kr@savex.in', 'asha.naik@savex.in']},
    92173: {'cc':['SumitSehgal@ecomexpress.in','sandeepc@ecomexpress.in', 'mukundh@ecomexpress.in'],'to':['swati.steren@gmail.com','shivani.steren@gmail.com', 'anand.steren@gmail.com', 'sudheer.steren@gmail.com', 'ashok.steren@gmail.com', 'bhaumitrasteren@gmail.com']},
    88185: {'cc':['veenav@ecomexpress.in','shilpaa@ecomexpress.in'],'to':['soumen.royal@gmail.com','somgyc@gmail.com','surendra.gupta019@gmail.com','kumar.digvijay341@gmail.com']},
    90180: {'cc':['veenav@ecomexpress.in','shilpaa@ecomexpress.in','swethaj@ecomexpress.in'],'to':['prasad.br@fashionara.com','sunil.kumar@fashionara.com']},
    87177: {'cc':['kalpanak@ecomexpress.in','veenav@ecomexpress.in','shilpaa@ecomexpress.in','swethaj@ecomexpress.in'],'to':['indranil.nath@zoffio.com','praveen.v@zoffio.com','omt@zoffio.com']},
    59162: {'cc':['amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['artisharma@indiarush.com', 'achalchawla@indiarush.com', 'bipin.kumar@indiarush.com', 'sushantg@ecomexpress.in', 'trinath.kundu@indiarush.com','achalchawla@indiarush.com','abdul.qadir@indiarush.com','mukundh@ecomexpress.in']},
    94020: {'cc':['Sumitsehgal@ecomexpress.in', 'amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['praveen.chamoli@dealskart.in','supratim.das@dealskart.in','vikesh.sanghotra@dealskart.in','mukundh@ecomexpress.in']},
    23158: {'cc':['sijur@ecomexpress.in', 'amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['richa.deb@moodsofcloe.com','soumya.kant@moodsofcloe.com','kamlesh.yadav@moodsofcloe.com','mukundh@ecomexpress.in']},
    84129: {'cc':['amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['sudhanshu@krishna-international.in','ashutosh@lensbazaar.com','service@lensbazaar.com','mukundh@ecomexpress.in']},
    51146: {'cc':['amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['info@fullkart.com','mukundh@ecomexpress.in']},  
    14161: {'cc':['amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['chatarpal@spademark.com', 'nikhil.sehgal@spademark.com']},
    72164: {'cc':['amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['Kt@fashionarena.in', 'namrata@fashionarena.in']},
    70133: {'cc':['amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['vidula@yellowfashion.in', 'shilpa@yellowfashion.in', 'priyanka@yellowfashion.in']},
    36152: {'cc':['amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['gadgetsngizmoss@gmail.com']},
    29151: {'cc':['amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['admin@store503.com']},
    18113: {'cc':['amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['sagar@hopshopdrop.com', 'varsha@hopshopdrop.com']},
    84144: {'cc':['amrins@ecomexpress.in','shalinia@ecomexpress.in'], 'to': ['samir@mapro.com', 'jay.joshi@xpointers.com']},
    30169: {'cc': ['sumitsehgal@ecomexpress.in', 'amrins@ecomexpress.in','shalinia@ecomexpress.in'],'to':['rto@astroscience.in','palwinder.singh@astroscience.in','logistics@astroscience.in', 'msi.logistics@astroscience.in']},
    33156: {'cc': ['amrins@ecomexpress.in','shalinia@ecomexpress.in'],'to':['vishal@stylestreetstore.com','sumit@stylestreetstore.com','rimjim@stylestreetstore.com','tarun@stylestreetstore.com', 'inder@streetstylestore.com', 'sumit@streetstylestore.com']},
    11007: {'cc': ['sandeep@ecomexpress.in', 'vaibhavk@ecomexpress.in','biswakantp@ecomexpress.in','jyotirmayc@ecomexpress.in','balwinders@ecomexpress.in'], 'to': ['sarithak@ecomexpress.in', 'vaibhavk@ecomexpress.in','biswakantp@ecomexpress.in','jyotirmayc@ecomexpress.in']},
    55131: {'cc': ['paritosh.Bindra@Luxuryretail.com', 'rsinha@ecomexpress.in'], 'to': ['jagdeep.sharma@luxuryretail.com']},
    80106: {'cc': ['amrins@ecomexpress.in', 'shankars@ecomexpress.in', 'shalinia@ecomexpress.in'], 'to': ['salauddin@thatspersonal.com']},
    76035: {'cc': ['rubys@ecomexpress.in','sanjeev@freecultr.com'], 'to': ['sharad@freecultr.com']},
    34004: {'cc': ['pawan.rathod@naaptol.com', 'avdesh.shukla@naaptol.com', 'niteshc@ecomexpress.in','puneet.virmani@naaptol.com', 'narendra.kumar@naaptol.com', 'vaibhavk@ecomexpress.in', 'Vinod.sharma@naaptol.com', 'Vikrant.kajla@naaptol.com', 'Rahul.sharma@naaptol.com', 'sandeep.pandey@naaptol.com'], 'to': ['vinay.sharma@naaptol.com', 'sachin.saurabh@naaptol.com', 'Dheeraj.sharma@naaptol.com', 'pickupdata@naaptol.com', 'Manoj.sharma@naaptol.com','ankit.jain@naaptol.com']},
    15110: {'cc': ['veenav@ecomexpress.in', 'shilpaa@ecomexpress.in', 'zeeshanm@ecomexpress.in', 'shwethaj@ecomexpress.in'], 'to': ['rahul@mebelkart.com', 'nikhil@mebelkart.com']},
    67081: {'cc': ['rsinha@ecomexpress.in'], 'to': ['mtvdelhi@gmail.com', 'sales@homeessence.in']},
    34064: {'cc': ['rsinha@ecomexpress.in'], 'to': ['info@hotdealstop.com', 'logistic@hotdealstop.com']},
    80126: {'cc': ['girraj.sharma@myntra.com', 'vaibhavk@ecomexpress.in', 'veenav@ecomexpress.in', 'shilpaa@ecomexpress.in', 'shwethaj@ecomexpress.in','zeeshanm@ecomexpress.in'], 'to': ['3pl-dailyreview@myntra.com','Aziz.baghadia@myntra.com','sudhish.as@myntra.com']},
    16018: {'cc': ['litstick@gmail.com', 'sunainas@ecomexpress.in'], 'to': ['info@litstick.com']},
    41107: {'cc': ['sushantg@ecomexpress.in', 'gurvinder.pahwa@shopclues.com', 'sunainas@ecomexpress.in', 'raman.preet@shopclues.com', 'mukundh@ecomexpress.in'], 'to': ['cl@shopclues.com']},
    65045: {'cc': ['utpal.lotlikar@slassy.com', 'veenav@ecomexpress.in', 'shilpaa@ecomexpress.in', 'zeeshanm@ecomexpress.in', 'shwethaj@ecomexpress.in'], 'to': ['manasa.g@slassy.com', 'rajkumar.srinivasan@slassy.com']},
    23071: {'cc': ['hampanna.k@bluestone.com', 'sunainas@ecomexpress.in', 'mukundh@ecomexpress.in', 'amrins@ecomexpress.in', 'shalinia@ecomexpress.in', 'shankars@ecomexpress.in'], 'to': ['hampanna.k@bluestone.com', 'priyanka.shill@bluestone.com', 'yatish.ohol@bluestone.com']},
    40098: {'cc': ['amrins@ecomexpress.in', 'shalinia@ecomexpress.in', 'shankars@ecomexpress.in', 'rsinha@ecomexpress.in'], 'to': ['suraj@beautykafe.com', 'pankaj@beautykafe.com', 'rukmani@beautykafe.com']},
    88101: {'cc': ['kalpanak@ecomexpress.in','veenav@ecomexpress.in', 'shilpaa@ecomexpress.in', 'zeeshanm@ecomexpress.in', 'shwethaj@ecomexpress.in'], 'to': ['orders@mynutramart.com', 'info@mynutramart.com']},
    96038: {'cc': ['lalit.kumar@yepme.com','ashish.chauhan@yepme.com', 'wamiq.dawood@yepme.com', 'ankur.gur@ecomexpress.in', 'rsinha@ecomexpress.in'], 'to': ['mukesh.kumar@yepme.com', 'suresh.thakur@yepme.com','mukesh.kumar@yepme.com']},
    35114: {'cc': ['sunainas@ecomexpress.in', 'santosh.sanas@nykaa.com', 'supriya.pednekar@nykaa.com', 'vijay.kg@nykaa.com', 'darshini.awad@nykaa.com', 'manoj.jaiswal@nykaa.com', 'shalinia@ecomexpress.in', 'rakeshp@ecomexpress.in', 'mukundh@ecomexpress.in'], 'to': ['Logistics@nykaa.com', 'cs@nykaa.com']},
    43051: {'cc': ['siddharth@bewakoof.com', 'vaibhavk@ecomexpress.in'], 'to': ['altamash@bewakoof.com', 'care@bewakoof.com']},
    92082: {'cc': ['vaibhavk@ecomexpress.in'], 'to': ['amit27verma@yahoo.com', 'ashok.sharma@gadgetcops.com']},
    96047: {'cc': ['kalpanak@ecomexpress.in','shwethaj@ecomexpress.in', 'veenav@ecomexpress.in', 'zeeshanm@ecomexpress.in', 'shilpaa@ecomexpress.in'], 'to': ['lochana@zivame.com', 'panindra@zivame.com', 'sabeeya@milastar.in', 'devika@zivame.com', 'ali@milastar.in']},
    88008: {'cc': ['rubys@ecomexpress.in','sushma.singh@xerionretail.com','puneet.nasa@xerionretail.com', 'vaibhavk@ecomexpress.in'], 'to': ['nikhil.kumar@xerionretail.com', 'daljeet@xerionretail.com','azad.khan@xerionretail.com', 'preeti.pandey@xerionretail.com', 'Logisticsmis@xerionretail.com']},
    37042: {'cc': ['homecheck42@gmail.com', 'acasakshijain@gmail.com', 'arvind@home-check.net.in', 'mukundh@ecomexpress.in'], 'to': ['arvind.jha2007@gmail.com']},
    43017: {'cc': ['nandan.kumar@infibeam.net', 'kumar.rahul@infibeam.net', 'sourav.bhattacharya@infibeam.net', 'shayoob.pasha@infibeam.net', 'zuhaib.ahmed@infibeam.net', 'vijayendra.kudale@infibeam', 'rajesh.pawar@infibeam.net', 'gajendra.attri@infibeam.net', 'rsinha@ecomexpress.in'], 'to': ['iblsupport@infibeam.net']},
    32056: {'cc': ['lakshit@toytoy.com', 'naveen@toytoy.com', 'sunainas@ecomexpress.in', 'mukundh@ecomexpress.in'], 'to': ['neha@toytoy.com']},
    12075: {'cc': ['santosh@xcitejewellery.com', 'rsinha@ecomexpress.in'], 'to': ['mumbai@taraash.com']},
    57055: {'cc': ['kalpanak@ecomexpress.in','veenav@ecomexpress.in', 'shilpaa@ecomexpress.in', 'zeeshanm@ecomexpress.in', 'shwethaj@ecomexpress.in'], 'to': ['sagar@sports365.in', 'moy@sports365.in', 'kalpana@sports365.in', 'satish@sports365.in', 'praveen@sports365.in', 'naresh@sports365.in']},
    71102: {'cc': ['Sumitsehgal@ecomexpress.in', 'sreekanth@limeroad.com', 'sunainas@ecomexpress.in', 'mukundh@ecomexpress.in'], 'to': ['nandkishor@limeroad.com','CS@limeroad.com']},
    81013: {'cc': ['sushantg@ecomexpress.in', 'mukundh@ecomexpress.in','vaibhavk@ecomexpress.in', 'ajit.kumar@fashionandyou.com'], 'to': ['anshumaan.sambyal@fashionandyou.com', 'sonam.kumar@fashionandyou.com', 'richa@fashionandyou.com', 'waris.ansari@fashionandyou.com', 'pranabesh.adhikari@fashionandyou.com', 'pooja.lal@fashionandyou.com', 'anuj.sharma@fashionandyou.com']},
    59072: {'cc': ['veenav@ecomexpress.in', 'shilpaa@ecomexpress.in', 'zeeshanm@ecomexpress.in', 'shwethaj@ecomexpress.in'], 'to': ['sreenivas.p@playgroundonline.com']},
    97089: {'cc': ['amrins@ecomexpress.in', 'shankars@ecomexpress.in', 'sunainas@ecomexpress.in', 'shalinia@ecomexpress.in', 'mukundh@ecomexpress.in'], 'to': ['vipul@20dresses.com', 'hello@20Dresses.com']},
    19019: {'cc': ['sunainas@ecomexpress.in', 'manav.gupta@v4ushopping.com', 'leena.gupta@v4ushopping.com', 'mukundh@ecomexpress.in'], 'to': ['logistics@v4ushopping.com']},
    69060: {'cc': ['sunainas@ecomexpress.in', 'vandanab@rediff.co.in', 'amrins@ecomexpress.in', 'shalinia@ecomexpress.in', 'mukundh@ecomexpress.in'], 'to': ['kamleshg@rediff.co.in', 'jayeshp@rediff.co.in', 'sarun@rediff-inc.com', 'vandanab@rediff.co.in']},
    76088: {'cc': ['pranav@bluebustees.com', 'mukundh@ecomexpress.in', 'shalinia@ecomexpress.in'], 'to': ['info@bluebustees.com']},
    82120: {'cc': ['front.office@allschoolstuff.com', 'Manoj.chandra@allschoolstuff.com', 'Ankur.dinesh@allschoolstuff.com', 'suresh.kumar@allschoolstuff.com', 'operations2@allschoolstuff.com', 'shalinia@ecomexpress.in'], 'to': ['bajrang.kumar@allschoolstuff.com', 'support2@allschoolstuff.com']},
    22092: {'cc': ['manu.bhatia@flipkart.com', 'saurabh.jain@ekartlogistics.com', 'meena.sb@flipkart.com', 'richardp@wsretail.in', 'arunraj@wsretail.in', 'solomon.richard@flipkart.com', 'cstcoreteam@ekartlogistics.com', 'manish.srinivasan@flipkart.com', 'shwethaj@ecomexpress.in', 'veenav@ecomexpress.in', 'zeeshanm@ecomexpress.in', 'shilpaa@ecomexpress.in'], 'to': ['dhananjay.c@ekartlogistics.com', 'vikashk@ekartlogistics.com']},
    66103: {'cc': ['dharmesh.raja@themobilestore.in', 'sujitha.nayak@themobilestore.in', 'arif.shaikh@themobilestore.in',  'shalinia@ecomexpress.in'], 'to': ['rsujoy@themobilestore.in']},
    79032: {'cc': ['himpriyasingh@vgmail.in','arvindtomar@vgmail.in','yogeshpal@vgmail.in', 'ashwanisaini@vgmail.in', 'ajay.singh@next.co.in', 'brajenderkumar@vgmail.in',  'saumikm@vgmail.in'], 'to': ['Mohit.pathak@vgmail.in', 'arvindtomar@vgmail.in', 'jiteshsharma@vgmail.in', 'rsinha@ecomexpress.in', 'saumikm@vgmail.com']},
    71117: {'cc': ['nikhil.kumar@bestylish.com', 'sunil.nayak@bestylish.com', 'suneel.kumar@bestylish.com', 'dhananjay.singh@bestylish.com', 'rsinha@ecomexpress.in'], 'to': ['mohan.agarwal@bestylish.com']},
    34125: {'cc': ['agent21@trendin.com', 'agent14@trendin.com', 'kalpanak@ecomexpress.in','amitkumar.singh@madura.adityabirla.com', 'abhishek.jha@madura.adityabirla.com', 'veenav@ecomexpress.in','agent8@trendin.com', 'shilpaa@ecomexpress.in', 'zeeshanm@ecomexpress.in', 'shwethaj@ecomexpress.in', 'santhosh@trendin.com', 'santhosh.chinnaswamy@madura.adityabirla.com'], 'to': ['rasheed.khan@madura.adityabirla.com', 'gayathri.p@madura.adityabirla.com', 'santosh@trendin.com']},
    87121: {'cc': ['amrins@ecomexpress.in', 'shankars@ecomexpress.in', 'logistics@mulyashop.com','pinky.jadhwani@mulyashop.com', 'verifier@mulyashop.com', 'shalinia@ecomexpress.in'], 'to': ['shashank@mulyashop.com', 'logistics@mulyashop.com']},
    13010: {'cc': ['SumitSehgal@ecomexpress.in','sunainas@ecomexpress.in', 'Manish.jain@indiatimes.co.in', 'puneet.sharma@indiatimes.co.in', 'mukundh@ecomexpress.in', 'sandeepc@ecomexpress.in'], 'to': ['Sadhna.singh@indiatimes.co.in','Meenakshi.dudeja@timesinternet.in','Kamlakant.upadhyay@timesinternet.in']},
    46036: {'cc': ['kailash.sati@koovs.com', 'manish@koovs.com', 'Surjeet.singh@koovs.com', 'mohan@koovs.com', 'rsinha@ecomexpress.in'], 'to': ['ranjeet@koovs.com']},
    15066: {'cc': ['kalpanak@ecomexpress.in','siddharth@liveyoursport.com', 'sony@liveyoursport.com','ram@liveyoursport.com','punith@liveyoursport.com', 'veenav@ecomexpress.in', 'shilpaa@ecomexpress.in', 'zeeshanm@ecomexpress.in', 'shwethaj@ecomexpress.in'], 'to': ['arathi@liveyoursport.com']},
    96093: {'cc': ['mukundh@ecomexpress.in'], 'to': ['dhruv@globalkars.com']},
    69087: {'cc': ['rsinha@ecomexpress.in'], 'to': ['avneet9999@gmail.com']},
    24059: {'cc': ['vishakha@stalkbuylove.com', 'priyanka.s@stalkbuylove.com', 'nishrit@stalkbuylove.com', 'rsinha@ecomexpress.in'], 'to': []},
    53094: {'cc': ['sprabhat2005@yahoo.co.in', 'rsinha@ecomexpress.in'], 'to': ['sainiprabhat@yahoo.co.in']},
    92006: {'cc': ['vaibhavk@ecomexpress.in', 'ajaykumar@ecomexpress.in','megha.chauhan@snapdeal.com','raman.sood@snapdeal.com','ahmad.mohd@snapdeal.com', 'megha.chauhan@snapdeal.com', 'ravikanth.k@jasperindia.com','shantanu.chakraborty@snapdeal.com', 'shantanu.chakraborty@jasperindia.com', 'ajay.yadav@jasperindia.com', 's.lakshmanan@snapdeal.com', 'sunainas@ecomexpress.in', 'kumar.avinash@snapdeal.com', 'Sunil.singh@snapdeal.com', 'ajay.yadav@snapdeal.com', 'sumitsehgal@ecomexpress.in','amrishn@ecomexpress.in'], 'to': ['gaurav.sharma@snapdeal.com','mohit.joshi@snapdeal.com','jagnarayan.prasad@snapdeal.com', 'lalit.bharti@snapdeal.com', 'anil.sharma@snapdeal.com']},
    49127: {'cc': ['sumit@jaypore.com'], 'to': ['amandeep.bhasin@jaypore.com']},
    56041: {'cc': ['baldeep@datawind.com', 'rishi.bhasin@datawindcorp.com', 'vaibhavk@ecomexpress.in'], 'to': ['maninder@datawindcorp.com', 'shalu.malhotra@datawindcorp.com', 'satyendra@datawindcorp.com']},
    56200: {'cc': ['ruchikas@ecomexpress.in', 'baldeep@datawind.com', 'rishi.bhasin@datawindcorp.com', 'vaibhavk@ecomexpress.in'], 'to': ['maninder@datawindcorp.com', 'shalu.malhotra@datawindcorp.com', 'satyendra@datawindcorp.com', 'roy@datawindcorp.com', 'rupinder@datawind.com']},
    80108: {'cc': ['sumitsehgal@ecomexpress.in','piyush@mmionline.in', 'pushpendra@mmionline.in', 'hemant@mmionline.in'], 'to': ['nilamani@mmionline.in', 'mohitsrivastava@mmionline.in']},
    12016: {'cc': ['niteshc@ecomexpress.in','manisha.arora@texports.co.in', 'sourabh.maity@groupon.co.in', 'shwetabh.mishra@groupon.com', 'sunainas@ecomexpress.in', 'mukundh@ecomexpress.in'], 'to': ['cs@groupon.com', 'shashank.dubey@groupon.com']},
    67061: {'cc': ['Dinesh.Panchal@futuregroup.in', 'mukundh@ecomexpress.in', 'shalinia@ecomexpress.in'], 'to': ['Mandar.Mayekar@futuregroup.in']},
    80119: {'cc': ['mukundh@ecomexpress.in'], 'to': ['pardeep@okyvoky.com']},
    72057: {'cc': ['mukundh@ecomexpress.in'], 'to': ['support@karrymax.com','sales@karrymax.com','admin@karrymax.com','karrymaxretail@gmail.com']},
    25053: {'cc': ['sijur@ecomexpress.in', 'anand.sinha@99labels.com', 'satish.kumar@99labels.com', 'rsinha@ecomexpress.in'], 'to': ['logistics@99labels.com']},
    63039: {'cc': ['mmc@salora.com', 'anurag.mishra@salora.com', 'jsrawat@salora.com', 'rsinha@ecomexpress.in'], 'to': ['salzmartsalora@gmail.com']},
    49100: {'cc': ['abhishek.siddharth@shopnineteen.com', 'naresh.kumar@shopnineteen.com', 'ved.parkash@shopnineteen.com', 'ravender.gupta@shopnineteen.com', 'gobind.pahwa@shopnineteen.com', 'narinder.mahajan@shopnineteen.com', 'rsinha@ecomexpress.in'], 'to': ['saroj.kumar@shopnineteen.com']},
    47043: {'to': ['sharad.sharma@eretail.co.in', 'sanjay.basu@eretail.co.in'], 'cc': ['vaibhavk@ecomexpress.in','director@eretail.co.in','accounts@eretail.co.in']},
    70123: {'to': ['rajat@smokefree.in'], 'cc': ['shilpaa@ecomexpress.in']},
    49172: {'to':['manoj@compuindia.com','support@compuindia.com','noorani@compuindia.com'],'cc':['shwethaj@ecomexpress.in','veenav@ecomexpress.in','shilpaa@ecomexpress.in']},
    48134: {'to': ['akanksha@3wfashions.com', 'response@just-linen.com'], 'cc': ['shilpaa@ecomexpress.in', 'veenav@ecomexpress.in', 'shwethaj@ecomexpress.in']},
    15132: {'to': ['cs@cilory.com','nehat@cilory.com','dheerajk@cilory.com','vikasb@dewsolutions.in','rubys@ecomexpress.in'], 'cc': ['sijur@ecomexpress.in']},
    14079: {'cc': ['kalpanak@ecomexpress.in','veenav@ecomexpress.in', 'shilpaa@ecomexpress.in', 'zeeshanm@ecomexpress.in', 'shwethaj@ecomexpress.in'], 'to': ['ops@globalshiksha.com', 'patanjali@globalshiksha.com', 'raiysa@globalshiksha.com', 'shashank@globalshiksha.com']}}
