'''
Created on Sep 27, 2012

@author: Sirius
'''
from django.conf.urls.defaults import *

urlpatterns = patterns('reports.views',
                       url(r'^$','reports_dashboard'),
                       url(r'^coddeposit_confirmation/$','cod_deposit_confirmation'),
                       url(r'^ndr/$','ndr'),
                       url(r'^customer_status/$','customer_status_reports'),                       
                       url(r'^performance_analysis/$','performance_analysis'),
                       url(r'^strike_rate_analysis_location/$','strike_rate_analysis_location'),
                       url(r'^ageing_sop/$','ageing_sop'),
                       url(r'^noinfo/$','noinfo'),
                       url(r'^backdated/$','backdated'),
                       url(r'^previousday/$','previousday'),
                       url(r'^cod_collection/$','cod_collection'),
                       url(r'^cod_collection_del/$','cod_collection_pod'),
                       url(r'^cod_collection_rev/$','cod_collection_pod_rev'),
                       url(r'^tally_input_xml/$','tally_input_xml'),
                       url(r'^cod_collection/daytally/$','cod_collection_daytally'),
                       url(r'^sc_emp/$','sc_emp'),
                       url(r'^daily_sales_register/$','daily_sales_register'),
                       url(r'^customer_wise_day_wise_sales_summary/$','customer_wise_day_wise_sales_summary'),
                       url(r'^customer_wise_bill_summary/$','customer_wise_bill_summary'),
                       url(r'^sub_customers/$', 'sub_customers'),                        
                       url(r'^sub_customers_report_view/$', 'sub_customers_report_view', name='sub-customer-report'),
                       url(r'^sub_customer_report/(?P<cid>\d+)/$', 'sub_customer_report', name='excel_sub_customer_report'),
                       url(r'^get_daily_report/$','get_daily_report', name='get-daily-report'),
                       url(r'^daily_report/$','daily_report', name='daily-report'),
                       url(r'^delivery_dispatch/$','delivery_dispatch'),
		       url(r'^day_wise_count/$','day_wise_count'),
		       url(r'^delivery_performance/$','delivery_performance'),
		       url(r'^not_outscan/$','not_outscan'),
		       url(r'^bag-exception-outbound/$','bag_exception_outbound'),
                       url(r'^bag-exception-inbound/$', 'bag_exception_inbound'),
                       url(r'^bag-exception-unconnected/$', 'bag_exception_unconnected'),
                       url(r'^bag-inscan-unconnected/$', 'bag_inscan_unconnected'),
                       url(r'^bag-hub-inscanned/$', 'bag_hub_inscanned'),
	               url(r'^bag_detail/$','bag_detail'),
		       url(r'^data_uploaded_status/(?P<stat>\d+)/$','data_uploaded_status'),
		       url(r'^hub_notoutscan/$','hub_notoutscan'),
                       url(r'^cust_reconcilation_report/$','cust_reconcilation_report'),
	               url(r'^bag_inbound/(?P<stat>\d+)/$','bag_inbound'),
                       url(r'^outscan_for_shipment/$','outscan_for_shipment'),
                       url(r'^get_inscan_report/$','get_inscan_report', name='get-inscan-report'),
                       url(r'^inscan_report/$','inscan_report', name='inscan-report'),
                       url(r'^get_prev_day_load_report/$','get_prev_day_load_report', name='get-prev-day-load-report'),
                       url(r'^prev_day_load_report/$','prev_day_load_report', name='prev-day-load-report'),
                       url(r'^strike_rate_analysis_customer/$','strike_rate_analysis_customer'),
                       url(r'^performance_analysis_customer/$','performance_analysis_location', {'rtype':'1'}),
                       url(r'^weekly_report/$','weekly_report'),                       
		       url(r'^performance_analysis_location/$','performance_analysis_location'),
                       url(r'^get_missed_pickup/$','get_missed_pickup', name='get-missed-pickup'),
                       url(r'^missed_pickup/$','missed_pickup', name='missed-pickup'),
                       url(r'^rto_status_report/$','rto_status_report', name='missed-pickup'),
                       url(r'^outscan_performance_report/$','outscan_performance_report'),
                       url(r'^correction_report/$','get_correction_report'),
                       url(r'^telecalling_report/$','telecalling_report'), 
                       url(r'^pickup_report/$','pickup_mis_report'), 
                       url(r'^overage_report/$','overage_reports'),
                       url(r'^shortage_report/$','shortage_reports'),
                       url(r'^trf_invice_report/$','trf_invice_report'),
                       url(r'^checked/$','checked'),
                       url(r'daily_cash_tally_report/', 'daily_cash_tally_report'),
                       url(r'west_bengal_report/','west_bengal_report'),
                       url(r'status_report/','status_report'),
                       url(r'daywise_report/$', 'daywise_report', name='daywise_report'),
                       url(r'^get_city_details/$', 'get_city_details', name='get_city_details'),
                       url(r'^get_region_details/$', 'get_region_details', name='get_region_details'),
                       url(r'^report-search/$', 'report_search', name='report_search'),
                       )
