# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_notifications', '0003_chatmentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmentions',
            name='creator',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    null=True,
                                    related_name='chat_mentioned_users',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storymentions',
            name='creator',
            field=models.ForeignKey(default=None,
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='story_mentioned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmentions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_in_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storymentions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_in_story', to=settings.AUTH_USER_MODEL),
        ),
    ]
