# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_notifications', '0004_auto_20160705_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteMentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='note_mentioned_users', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_in_note', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v2_email_notifications_notementions',
            },
        ),
        migrations.AddField(
            model_name='emailnotificationqueue',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Note'),
        ),
        migrations.AddField(
            model_name='emailoptions',
            name='project_events',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Never'), (1, b'Watched Projects'), (2, b'All Projects')], default=1, help_text=b'A Project Event'),
        ),
        migrations.AlterField(
            model_name='chatmentions',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chat_mentioned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storymentions',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='story_mentioned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
