# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20160113_1204'),
        ('organizations', '0002_auto_20151204_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, b'Unread'), (1, b'Read'), (2, b'Archived')], default=0)),
                ('subject', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
