# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20160113_1204'),
        ('organizations', '0002_auto_20151204_1248'),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='inboxentry',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='inboxentry',
            name='project',
        ),
        migrations.RemoveField(
            model_name='inboxentry',
            name='story',
        ),
        migrations.RemoveField(
            model_name='inboxentry',
            name='user',
        ),
        migrations.AddField(
            model_name='inboxentry',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inbox.InboxGroup'),
            preserve_default=False,
        ),
    ]
