# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 06:48
from __future__ import unicode_literals

import apps.attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_tmpattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpattachment',
            name='sessionkey',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tmpattachment',
            name='attachment_file',
            field=models.FileField(max_length=512, upload_to=apps.attachments.models.attachment_temp_attachment_upload, verbose_name='attachment'),
        ),
    ]
