# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160113_1204'),
        ('attachments', '0004_auto_20160204_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpattachment',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.Project'),
            preserve_default=False,
        ),
    ]
