# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_tmpattachment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='cover_image',
            field=models.BooleanField(default=False),
        ),
    ]
