# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 13:05
from __future__ import unicode_literals

import apps.attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0006_noteattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteattachment',
            name='attachment_file',
            field=models.FileField(max_length=512,
                                   upload_to=apps.attachments.models.attachment_note_attachment_upload,
                                   verbose_name='attachment'),
        )

    ]
