# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-16 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0006_attachment_cover_image'),
        ('attachments', '0007_auto_20160825_1305'),
    ]

    operations = [
    ]
