# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 20:19
from __future__ import unicode_literals

import apps.avatar.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, max_length=1024, upload_to=apps.avatar.models.avatar_file_path)),
                ('date_uploaded', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

    # def apply(self, project_state, schema_editor, collect_sql=False):
    #     try:
    #         return super(Migration, self).apply(project_state, schema_editor, collect_sql)
    #     except:
    #         print 'Skipping avatar migration'
    #         pass
