'''
Created on Oct 22, 2012

@author: Sirius
'''
from django.conf.urls.defaults import *
from hub.views import mass_updation

urlpatterns = patterns('delivery.views',
            url(r'^$','inscan_bag'),
            url(r'^deposits/$','cash_deposit'),
            url(r'^add_coddeposit/$','add_coddeposit'),
            url(r'^inscan_shipment/$','inscan_shipment'),
            url(r'^rto_shipments/$','return_rto_shipments'),
            url(r'^redirection/$','redirection'),
            url(r'^connection_tallied/$','connection_tallied'),
            url(r'^inscan_shipment/revert/$','revert_inscan_shipment', name='revert-inscan-shipment'),
            url(r'^outscan/$','outscan'),
            url(r'^outscan_batch/$','outscan_batch'),
            url(r'^include_shipment/(?P<oid>\w+)/$','include_shipment'),
            url(r'^delink_shipment/(?P<oid>\w+)/$','delink_shipment'),
            url(r'^sal_excel_download/(?P<sid>\w+)/$','sal_excel_download'),
            url(r'^close_outscan/$','close_outscan'),
            url(r'^mass_updation/$',mass_updation,{'rtype':'1'}),
            url(r'^status_update/$','status_update'),
            url(r'^sal_tally/$','sal_tally'),
            url(r'^include_shipment_sal/(?P<sid>\w+)/$','include_shipment_sal'),
            url(r'^delink_shipment_sal/(?P<sid>\w+)/$','delink_shipment_sal'),
            url(r'^include_shipment_codd/(?P<cid>\w+)/$','include_shipment_codd'),
            url(r'^delink_shipment_codd/(?P<cid>\w+)/$','delink_shipment_codd'),
            url(r'^cash_tally/$','cash_tally', name='cash-tally'),
            url(r'^cash_tally/add_shipment/$','add_shipment'),
            url(r'^cash_tally/update_shipment_collected_value/$','update_shipment_collected_value'),
            url(r'^return_redirection/(?P<rtype>\w+)/$','return_redirection'),
            url(r'^delivery_sheet/(?P<oid>\w+)/$','delivery_sheet'),
            url(r'^delivery_sheet_sal/(?P<sid>\w+)/$','delivery_sheet_sal'),
            url(r'^deposit_sheet/(?P<cid>\w+)/$','deposit_sheet'),
            url(r'^close_codd/$','close_codd'),
            url(r'^awb_tally/$','awb_tally'),
            url(r'^cash_tally_deposits/$','cash_tally_deposits'),
            url(r'^cash_tally/delivered_cash_tally/$', 'delivered_cash_tally'),
            url(r'^denomination/$','denomination'),
            url(r'^cash_denomination/(?P<cid>\w+)/$','cash_denomination'),
            url(r'^bag_tallied/$','bag_tallied'),
            url(r'^list_shipments/$','list_shipments'),
            url(r'^close_sal/$','close_sal'),
            url(r'^rts_pod_update/$','rts_pod_update'),
            url(r'^rts/$','rts_update'),
            url(r'^rto_reverse/$','rto_reverse'),
            url(r'^awb_info/$','awb_info'),
            url(r'^monitoring_dashboard/$','monitoring_dashboard'),
            url(r'^get_shipment_monitoring/$','get_shipment_monitoring'),
            url(r'^get_outscan_details/$', 'get_outscan_details'),
            url(r'^get_awbno_details/$', 'get_awbno_details'),
            url(r'^update_outscan_details/$', 'update_outscan_details'),
            url(r'^credit_card_payment/$', 'credit_card_payment'),
            url(r'^undel_awb_info/$','undel_awb_info'),
            url(r'^update_card_payment/$','update_card_payment'),
            url(r'^card_payment_report/$','card_payment_report'),
            url(r'^view_edit/$','view_edit'),
            url(r'^awb_credit_details/$','awb_credit_details'),
            url(r'^cod_panel/$','cod_panel', name='codpanel'),
            url(r'^cod_panel/coddeposits_search/$', 
                'cod_panel_coddeposit_search', 
                name='codpanel-coddeposit-search'),
)
