# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='oauth_token',
            field=models.CharField(max_length=255),
        ),
    ]
