# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0002_auto_20160112_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecampcredentials',
            options={'managed': False},
        ),
    ]
