# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_auto_20151204_1248'),
    ]

    operations = [

        migrations.AlterField(
            model_name='storyqueue',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='syncronizationqueue',
            name='action',
            field=models.IntegerField(choices=[(1, b'SYNC_REMOTE'), (2, b'STORY_UPDATED'), (3, b'STORY_DELETED'), (4, b'STORY_CREATED'), (5, b'INITIAL_SYNC'), (6, b'ACTION_STORY_STATUS_CHANGED'), (7, b'ACTION_TASK_UPDATED'), (8, b'ACTION_TASK_DELETED'), (9, b'ACTION_TASK_CREATED'), (10, b'ACTION_TASK_STATUS_CHANGED'), (11, b'ACTION_STORY_IMPORTED')]),
        ),
    ]
