from django.conf.urls.defaults import *
from django.contrib.auth import views as auth_views
from authentication import views as auviews

#urlpatterns = patterns('',
#                       url(r'^password/change/$',
#                           auth_views.password_change,
#                           name='auth_password_change'),
#                       url(r'^password/change/done/$',
#                           auth_views.password_change_done,
#                           name='auth_password_change_done'),
#                       url(r'^password/reset/$',
#                           auviews.employee,
#                           name='auth_password_reset'),
#                       url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
#                           auth_views.password_reset_confirm,
#                           name='auth_password_reset_confirm'),
#                       url(r'^password/reset/complete/$',
#                           auth_views.password_reset_complete,
#                           name='auth_password_reset_complete'),
#                       url(r'^password/reset/done/$',
#                           auth_views.password_reset_done,
#                           name='auth_password_reset_done'),
#
#
#)

urlpatterns = patterns('authentication.views',
                       url(r'^$','login_authenticate'),
                       url(r'^outemp/$','outemp'),
                       url(r'^employee/$','employee'),
                       url(r'^registration/$','employee_registration'),
                       url(r'^edit_employee/(?P<id>\w+)/$','edit_employee'),
                       url(r'^delete_employee/(?P<id>\w+)/$','delete_employee'),
                       url(r'^change_password/$','change_password'),
                       url(r'^update_password/$','update_password'),
                       url(r'^logout_view/$','logout_view'),
                       
                       url(r'^active_employee/(?P<id>\w+)/$','active_employee'),
                       url(r'^deactive_employee/(?P<id>\w+)/$','deactive_employee'),
                       url(r'^resetpassword/$','myresetpassword'),
                       url(r'^mass_employee_creation/$','mass_employee_creation'),          
                       url(r'^password/change/$',
                           auth_views.password_change,
                           name='auth_password_change'),
                       url(r'^password/change/done/$',
                           auth_views.password_change_done,
                           name='auth_password_change_done'),
                       url(r'^password/reset/$',
                           auth_views.password_reset,
                           name='auth_password_reset'),
                       url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
                           auth_views.password_reset_confirm,
                           name='auth_password_reset_confirm'),
                       url(r'^password/reset/complete/$',
                           auth_views.password_reset_complete,
                           name='auth_password_reset_complete'),
                       url(r'^password/reset/done/$',
                           auth_views.password_reset_done,
                           name='auth_password_reset_done'),
                       )
