# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient

def test_recordingSuite1():
    client = WindmillTestClient(__name__)

    client.click(xpath=u"//map[@id='header']/area[5]")
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(timeout=u'8000', id=u'id_username')
    client.click(id=u'id_username')
    client.type(text=u'windmill_test', id=u'id_username')
    client.type(text=u'klug', id=u'id_password1')
    client.type(text=u'klug', id=u'id_password2')
    client.type(text=u'windmill_test@wpidalamar.com', id=u'id_email')
    client.click(value=u'Create Account \xbb')
    client.waits.forPageLoad(timeout=u'20000')


