# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailconfirmation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
