# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20151204_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcell',
            name='steps',
            field=models.ManyToManyField(db_table=b'v2_kanban_boardcell_steps', related_name='cells', to='kanban.WorkflowStep'),
        ),
    ]
