# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20160112_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfdcache',
            name='iteration',
        ),
        migrations.RemoveField(
            model_name='cfdcache',
            name='project',
        ),
        migrations.RemoveField(
            model_name='cfdcache',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='cfdcachedstory',
            name='story',
        ),
        migrations.RemoveField(
            model_name='cfdcachedstory',
            name='value',
        ),
        migrations.RemoveField(
            model_name='cfdcachedvalue',
            name='cache',
        ),
        migrations.RemoveField(
            model_name='cfdcachedvalue',
            name='step',
        ),
        migrations.DeleteModel(
            name='CFDCache',
        ),
        migrations.DeleteModel(
            name='CFDCachedStory',
        ),
        migrations.DeleteModel(
            name='CFDCachedValue',
        ),
    ]
