# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20160113_1204'),
        ('kanban', '0004_auto_20160223_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('report_type', models.CharField(max_length=5)),
                ('y_axis', models.SmallIntegerField(default=1)),
                ('cfd_show_backlog', models.BooleanField(default=False)),
                ('tag', models.CharField(default=None, max_length=100, null=True)),
                ('last_generated', models.DateTimeField(null=True)),
                ('last_manual_view', models.DateField(null=True)),
                ('last_auto_view', models.DateField(null=True)),
                ('views', models.IntegerField(default=0)),
                ('assignee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('epic', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.Epic')),
                ('label', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.Label')),
                ('lead_end_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kanban.WorkflowStep')),
                ('lead_start_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kanban.WorkflowStep')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.Workflow')),
            ],
        ),
    ]
