# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_savedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='date_format',
            field=models.SmallIntegerField(choices=[(0, b'Fixed Dates'), (2, b'Relative Dates')], default=0),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='interval',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
