# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_auto_20160226_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='created',
            field=models.DateField(auto_created=True, default=datetime.date(2016, 2, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedreport',
            name='enddate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='startdate',
            field=models.DateField(default=None, null=True),
        ),
    ]
