# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160113_1204'),
        ('kanban', '0007_auto_20160226_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='iteration',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.Iteration'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
