# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_auto_20160229_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='burn_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='aging_type',
            field=models.SmallIntegerField(choices=[(0, b'Step'), (1, b'Tag')], default=0),
        ),
    ]
