# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0010_auto_20160301_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='aging_tags',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
