# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0012_savedreport_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcell',
            name='minPointLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardcell',
            name='minWipLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policy',
            name='min_related_value',
            field=models.IntegerField(default=0),
        ),
    ]
