# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0013_auto_20160511_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedreport',
            name='report_type',
            field=models.CharField(max_length=10),
        ),
    ]
