# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0014_auto_20160602_0129'),
        ('kanban', '0014_auto_20160603_1042'),
    ]

    operations = [
    ]
