# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 05:05
from __future__ import unicode_literals

from django.db import migrations

def removePendingRebuildMovementJob(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    RebuildMovementJob = apps.get_model("kanban", "RebuildMovementJob")

    for project in Project.objects.all():
        RebuildMovementJob.objects.filter(project=project).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_merge'),
        ('kanban', '0016_auto_20160628_1527'),
    ]

    operations = [
        migrations.RunPython(removePendingRebuildMovementJob, lambda a, b: None),
    ]
