# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0017_auto_20160704_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
