# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-16 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0018_savedreport_assignees')
    ]

    operations = [
    ]
