# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 08:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='order',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='projectshare',
            name='tag',
            field=models.CharField(default=b'public', max_length=64),
        ),
        migrations.AlterField(
            model_name='story',
            name='assignee',
            field=models.ManyToManyField(blank=True, db_table=b'v2_projects_story_assignee_m2m', related_name='assigned_stories', to=settings.AUTH_USER_MODEL, verbose_name='assignees'),
        ),
        migrations.AlterField(
            model_name='story',
            name='card_type',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
