# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160112_0843'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='story',
            unique_together=set([('local_id', 'project')]),
        ),
    ]
