# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160113_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectshare',
            name='assignee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='business_value',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='custom1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='custom2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='custom3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='detail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='epic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='points',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='tasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='time_estimates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='time_logged',
            field=models.BooleanField(default=True),
        ),
    ]
