# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160113_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shared',
            field=models.CharField(blank=True, default=b'', max_length=25, null=True),
        ),
    ]
