# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160322_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectshare',
            name='time_logged',
        ),
    ]
