# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160321_0827'),
        ('projects', '0005_remove_projectshare_time_logged'),
    ]

    operations = [
    ]
