# Generated by Django 1.9.1 on 2016-04-13 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_time_tracking_mode'),
        ('projects', '0006_merge'),
        ('projects', '0005_project_parent'),
    ]

    operations = [
    ]
