# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='points',
            field=models.CharField(blank=True, default=b'?', max_length=4, verbose_name=b'points'),
        ),
    ]
