# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:41
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count

import logging

logger = logging.getLogger(__name__)


def remove_duplicates(apps, schema_editor):
    Commit = apps.get_model("projects", "Commit")
    for c in Commit.objects.values("link", "story_id").annotate(Count("id")).order_by("link", "story_id").filter(id__count__gt=1):
        todelete = Commit.objects.filter(link=c['link'], story_id=c['story_id'])[1:]
        for commit in todelete:
            commit.delete()



class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0008_auto_20160418_0317'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together=set([('story', 'link')]),
        ),
    ]
