# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160503_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
