# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160406_1522'),
        ('projects', '0010_auto_20160503_1556'),
    ]

    operations = [
    ]
