# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='accumulated_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='last_moved',
            field=models.DateTimeField(default=None, null=True),
        )
    ]
