# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_value_mode',
            field=models.IntegerField(default=0),
        ),
    ]
