# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_story_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryBlocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('resolution', models.TextField()),
                ('blocked_date', models.DateTimeField(verbose_name='blocked_date')),
                ('unblocked_date', models.DateTimeField(verbose_name='unblocked_date')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_stories', to=settings.AUTH_USER_MODEL, verbose_name='blocker')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_instances', to='projects.Story')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_reasons', to='projects.Project')),
                ('unblocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unblocked_stories', to=settings.AUTH_USER_MODEL, verbose_name='unblocker')),
            ],
            options={
                'db_table': 'v2_projects_story_blocker',
            },
        ),
    ]
