# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_storyblocker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyblocker',
            name='unblocked_date',
            field=models.DateTimeField(null=True, verbose_name='unblocked_date'),
        ),
        migrations.AlterField(
            model_name='storyblocker',
            name='unblocker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unblocked_stories', to=settings.AUTH_USER_MODEL, verbose_name='unblocker'),
        ),
    ]
