# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_pointscale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='points',
            field=models.CharField(blank=True, default=b'?', max_length=7, verbose_name=b'points'),
        ),
    ]
