# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_business_value_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='business_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
