# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_merge'),
        ('projects', '0014_storyblocker_resolved'),
        ('projects', '0014_auto_20160514_1220'),
    ]

    operations = [
    ]
