# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='risk_reduction',
            field=models.CharField(blank=True, default=b'?', max_length=4, verbose_name=b'risk_reduction'),
        ),
        migrations.AddField(
            model_name='story',
            name='time_criticality',
            field=models.CharField(blank=True, default=b'?', max_length=4, verbose_name=b'time_criticality'),
        ),
    ]
