# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyblocker',
            name='external',
            field=models.BooleanField(default=False),
        ),
    ]
