# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20160525_1018'),
        ('projects', '0013_auto_20160519_0435'),
        ('projects', '0016_storyblocker_external'),
    ]

    operations = [
    ]
