# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20160603_0713'),
        ('projects', '0012_auto_20160518_1337'),
    ]

    operations = [
    ]
