# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20160603_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Team', max_length=48)),
                ('item_name', models.CharField(default=b'User Story', max_length=64)),
                ('level_number', models.SmallIntegerField(default=0)),
                ('icon', models.CharField(default=b'fa-users', max_length=32)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='projects.Portfolio')),
                ('projects', models.ManyToManyField(to='projects.Project')),
            ],
        ),
    ]
