# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 13:49
from __future__ import unicode_literals

from django.db import migrations, models


def copyParents(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for p in Project.objects.exclude(release_project=None):
        p.parents.add(p.release_project)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20160603_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parents',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_project_parents_+', to='projects.Project'),
        ),
        migrations.RunPython(copyParents, lambda a, b: None),
    ]
