# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='project',
            name='release_project',
        ),
        migrations.AlterField(
            model_name='project',
            name='parents',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='children',
                                         to='projects.Project'),
        ),
    ]
