# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aging_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='critical_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='warning_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='last_moved',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
