# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_portfolio_portfoliolevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliostorymapping',
            name='story',
        ),
        migrations.RemoveField(
            model_name='portfoliostorymapping',
            name='target_epic',
        ),
        migrations.RemoveField(
            model_name='portfoliostorymapping',
            name='target_project',
        ),
        migrations.DeleteModel(
            name='PortfolioStoryMapping',
        ),
    ]
