# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20160606_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='parents',
            field=models.ManyToManyField(blank=True, default=None, related_name='children', to='projects.Project'),
        ),
    ]
