# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20160609_1504'),
        ('projects', '0022_auto_20160614_1604'),
    ]

    operations = [
    ]
