# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prefix',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('organization', 'prefix')]),
        ),
    ]
