# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20151204_1248'),
        ('projects', '0024_auto_20160623_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliolevel',
            name='item_name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='organizations.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(default=b'fa-cube', max_length=48),
        ),
    ]
