# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='modified'),
        ),
    ]
