# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='dependency',
            field=models.ManyToManyField(blank=True, db_table=b'v2_projects_story_dependencies_m2m', related_name='dependent_stories', to='projects.Story', verbose_name='dependencies'),
        ),
    ]
