# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20160624_1433'),
        ('projects', '0023_auto_20160616_1040'),
    ]

    operations = [
    ]
