# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_notecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
