# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_merge'),
        ('projects', '0028_auto_20160627_1551'),
    ]

    operations = [
    ]
