# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramIncrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Iteration')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramIncrementSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('default_name', models.CharField(max_length=100)),
                ('increment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='projects.ProgramIncrement')),
            ],
        ),
        migrations.AddField(
            model_name='iteration',
            name='program_increment_schedule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProgramIncrementSchedule'),
        ),
    ]
