# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20160711_0939'),
        ('projects', '0027_note_active'),
        ('projects', '0030_auto_20160801_1537'),
    ]

    operations = [
    ]
