# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_story_dependency'),
        ('projects', '0031_merge'),
    ]

    operations = [
    ]
