# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliolevel',
            options={'ordering': ['level_number']},
        ),
        migrations.AlterField(
            model_name='iteration',
            name='program_increment_schedule',
            field=models.ForeignKey(blank=True, default=None, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='iterations',
                                    to='projects.ProgramIncrementSchedule'),
        ),
    ]

