# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20160825_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tab_board',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tab_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tab_dependencies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tab_planning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tab_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tab_teamplanning',
            field=models.BooleanField(default=True),
        ),
    ]
