# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20160906_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='project_assignments',
            field=models.ManyToManyField(related_name='assigned_stories', to='projects.Project'),
        ),
    ]
