# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_story_project_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamIterationWIPLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureLimit', models.PositiveSmallIntegerField(default=0)),
                ('featurePointLimit', models.PositiveSmallIntegerField(default=0)),
                ('cardLimit', models.PositiveSmallIntegerField(default=0)),
                ('cardPointLimit', models.PositiveSmallIntegerField(default=0)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Iteration')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
