# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_teamiterationwiplimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.DateTimeField(auto_now_add=True, verbose_name='assigned')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'db_table': 'v2_projects_story_project_assignments2',
            },
        ),
        migrations.RemoveField(
            model_name='story',
            name='project_assignments',
        ),
        migrations.AddField(
            model_name='projectassignments',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Story'),
        ),
        migrations.AddField(
            model_name='story',
            name='project_assignments2',
            field=models.ManyToManyField(related_name='assigned_stories', through='projects.ProjectAssignments', to='projects.Project'),
        ),
    ]
