# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20160928_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='project_assignments2',
            new_name='project_assignments',
        ),
        migrations.AlterModelTable(
            name='projectassignments',
            table='v2_projects_story_project_assignments',
        ),
    ]
