# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20160930_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tab_risks',
            field=models.BooleanField(default=True),
        ),
    ]
