# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20160928_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignments',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='projects.Story'),
        ),
    ]
