# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-29 02:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0039_auto_20160928_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='IterationSentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('number', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteration_sentiments', to=settings.AUTH_USER_MODEL)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='projects.Iteration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='projects.Project')),
            ],
            options={
                'db_table': 'v2_projects_iteration_sentiment',
            },
        ),
    ]
