# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_project_tab_risks'),
        ('projects', '0041_iteration_vision'),
    ]

    operations = [
    ]
