# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='time_period',
            field=models.CharField(default=b'Portfolio Increment', max_length=32),
        ),
        migrations.AddField(
            model_name='portfoliolevel',
            name='time_period',
            field=models.CharField(default=b'Iteration', max_length=32),
        ),
    ]
