# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-13 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20161007_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tab_milestones',
            field=models.BooleanField(default=False),
        ),
    ]
