# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-09 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20161107_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duedate_warning_threshold',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
    ]
