# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-19 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vision',
            field=models.TextField(blank=True, verbose_name=b'vision'),
        ),
    ]
