# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-20 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_project_vision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tab_summary',
            new_name='tab_sentiments',
        ),
    ]
