# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-14 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_auto_20161220_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='continuous_flow_iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.Iteration'),
        ),
    ]
