# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-15 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_project_continuous_flow_iteration'),
        ('projects', '0052_remove_programincrementschedule_end_date'),
    ]

    operations = [
    ]
