# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-02 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteration',
            name='program_increment_schedule',
        ),
        migrations.AddField(
            model_name='iteration',
            name='program_increment_schedule',
            field=models.ManyToManyField(blank=True, default=None, related_name='iterations', to='projects.ProgramIncrementSchedule'),
        ),
    ]
