# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-13 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_portfoliolevel_work_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_archive_iterations',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
    ]
