# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-18 15:50
from __future__ import unicode_literals

from django.db import migrations

from apps.projects.models import Project, Iteration

import logging

logger = logging.getLogger(__name__)


def convertReleasesToCF(a,b):
    projects = Project.objects.filter(project_type=2, continuous_flow_iteration=None, active=True)
    for project in projects:
        logger.info(project.slug)
        iterations = project.iterations.filter(iteration_type=Iteration.ITERATION_WORK)
        if iterations.count() > 0:
            project.continuous_flow_iteration = iterations[0]
            project.save()



class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_project_auto_archive_iterations'),
    ]

    operations = [
        migrations.RunPython(convertReleasesToCF, lambda a, b: None),
    ]
